# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{automaker}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ronald Evers"]
  s.date = %q{2010-11-28}
  s.default_executable = %q{automaker}
  s.description = %q{Will monitor a directory using fsevents api and call make when something changes. Only works on Mac OS X.}
  s.email = %q{ronaldpaulusevers@gmail.com}
  s.executables = ["automaker"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rvmrc",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "automaker.gemspec",
     "bin/automaker",
     "lib/automaker.rb",
     "spec/automaker_spec.rb"
  ]
  s.homepage = %q{http://github.com/ronaldevers/automaker}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Not autotest, not autospec, but automake(r)}
  s.test_files = [
    "spec/automaker_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fsevents>, [">= 0.1.1"])
    else
      s.add_dependency(%q<fsevents>, [">= 0.1.1"])
    end
  else
    s.add_dependency(%q<fsevents>, [">= 0.1.1"])
  end
end
