# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{automaker}
  s.version = "0.0.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ronald Evers"]
  s.date = %q{2009-12-15}
  s.default_executable = %q{automaker}
  s.description = %q{Will monitor a directory using fsevents api and call make when something changes.}
  s.email = %q{ronaldpaulusevers@gmail.com}
  s.executables = ["automaker"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/automaker.rb"
  ]
  s.homepage = %q{http://github.com/ronaldevers/automaker}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Not autotest, not autospec, but automake(r)}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fsevents>, [">= 0.1.1"])
    else
      s.add_dependency(%q<fsevents>, [">= 0.1.1"])
    end
  else
    s.add_dependency(%q<fsevents>, [">= 0.1.1"])
  end
end

